if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
install.packages("tidyverse")
BiocManager::install("QDNAseq", dependencies = TRUE)
BiocManager::install("Biobase")
BiocManager::install("CGHcall")
BiocManager::install("matrixStats")
BiocManager::install("R.utils")
BiocManager::install("Rsamtools")
BiocManager::install("future.apply", force = TRUE)
BiocManager::install("QDNAseq.hg19")
library(QDNAseq)
browseVignettes("QDNAseq")
bins <- getBinAnnotations(binSize=15)
bins
